### ISSUE TITLE
PAPI Counters same on ENTER and LEAVE

### ISSUE THREAD

**Issue by kisaacs** [khuck/xpress-apex#117]
We have a trace where otf2-print seems to indicate the ENTER and LEAVE have the same Counter values. I'm not sure if we're misinterpreting these or something else is happening.

This was taken on rostam using the Phylanx LRA spread across 16 threads. I've emailed the trace file.

**Comment by khuck** [comment]
I found the problem - the writer was writing the start value for both.  This is fixed in the most recent version of APEX which may or may not work with HPX currently.  There's a PR to merge in a big refactoring of the APEX/HPX integration which should be in HPX master by the end of the week.  If you want to cherry-pick these two code changes, they should be isolated.

**Comment by kisaacs** [comment]
Thanks @khuck !

**Comment by khuck** [comment]
fixed
