### ISSUE TITLE
Is it possible to get task level visualization of a trace file generated through APEX?

### ISSUE THREAD

**Issue by nithin-nod** [khuck/xpress-apex#129]
I am interested in obtaining a visualization of task level performance through trace files. Currently the generated trace file provides information at the hpx methods level as evidenced by the image below.

![1](https://user-images.githubusercontent.com/68087711/99008767-a7784380-24fb-11eb-8e6c-4f9567eaa9b3.png)
*visualization through vampir
Is there a possibility to obtain task level performance trace file (ex: hpx_main(), fibanocci()), essentially the methods inside which hpx objects reside. 

Reference program: https://github.com/STEllAR-GROUP/hpx/blob/master/examples/quickstart/fibonacci.cpp

Thank you.

**Comment by khuck** [comment]
That's a tricky question... the short answer is maybe, but probably not. :)

Because HPX tasks can start/end on different threads, OTF2 (the trace format) can't fully support those types of asynchronous timers, because OTF2 requires them to stay on the same pthread.  That's why we integrated APEX into the HPX runtime, so that it can support tracing the HPX tasks.  Unfortunately OTF2 is designed for traditional parallel computing models (MPI + pthreads or OpenMP).

If you are only concerned with profiling and/or task dependency graphs (like this: http://khuck.github.io/xpress-apex/usage/#profiling_with_taskgraph_output), you can try adding scoped timers, like this example: https://github.com/khuck/xpress-apex/blob/12d5cb56e06c0849099c4424ce768dba8b675045/src/examples/DemoCpp/demo.cpp#L13.  You'll need to include the `apex_api.hpp` header, too: https://github.com/khuck/xpress-apex/blob/12d5cb56e06c0849099c4424ce768dba8b675045/src/examples/DemoCpp/demo.cpp#L1

You might also have to run with the environment variable `export APEX_UNTIED_TIMERS=1` in that case, so that APEX doesn't maintain a timer stack per pthread (which is what OTF2 requires).

**Comment by nithin-nod** [comment]
Thank you so much for your response Kevin, this is super helpful. :)
Scoped timers provide critical information like time of each method and even call but can this scale across multiple processes and potentially across multiple nodes (my use case is using open-mpi with multiple nodes)? I tried spinning multiple processes but I ended up getting the same graph.

**Comment by khuck** [comment]
Ah, yes - one thing that is missing in APEX is to unify the measurements at program exit.  Currently, each process writes its own data to a separate file.  Sometime soon I would like to add some unification so that there is a single report for the whole execution, and one file representing the data from all ranks/processes.  If you'd like that I can try to make time for it.  In the meantime, you should get an output file for each rank/process if you are doing task graph output, or writing out CSV or TAU profiles.

**Comment by nithin-nod** [comment]
Unfortunately I am getting just a single task graph output even when running multiple processes. I did `cd xpress-apex/build/src/examples/DemoCpp; export APEX_TASKGRAPH_OUTPUT=1; mpirun -np 2 apexCppDemo`. I did get two csv/json output files though.

**Comment by khuck** [comment]
Oops, there's a bug...or it's intentional.  Try changing this line:

https://github.com/khuck/xpress-apex/blob/47021a5635e913e7249163d458f8b437694622be/src/apex/profiler_listener.cpp#L1420

to not test for the node_id.  Let me know if that works for you, if so I'll make the change permanent.

**Comment by nithin-nod** [comment]
That worked, thank you.
